SOURCES=main.cc input.cc util.cc
OBJS=$(patsubst %.cc,%.o, $(SOURCES))
CXXFLAGS=`pkg-config --cflags glibmm-2.4` -g 
LDFLAGS=`pkg-config --libs glibmm-2.4` -lelf
OTHER_INCLUDES="-I/usr/include/c++/4.3.0" -D__linux__ -I/usr/include/linux -I/usr/include/c++/4.3.0/tr1 -I/usr/include/c++/4.3.0/i386-redhat-linux/


ci: $(OBJS)
	g++ -o ci $(OBJS) $(LDFLAGS)

.cc.o: 
	g++ -c -o $@ $< ${CXXFLAGS}

clean:
	rm -f $(OBJS)

depends: .depends

dependclean:
	rm -f .depends
.depends:
	touch .depends
	makedepend -f.depends -s'# AUTOGENERATED - Modifications will be overwritten'  `g++ -print-search-dirs | grep programs | cut -d'=' -f'2-' | sed -e 's/^/ -I/' | sed -e 's/:/ -I/'g`  ${CXXFLAGS} ${OTHER_INCLUDES}  ${SOURCES}
	make -C .

-include .depends

